Port to Python 3
jeffreydwalter/arlo pull request #12
Opened 2017-07-18 11:23 UTC by andijakl

Ported the scripts to run on Python 3 (after all, Python 2 won't be maintained anymore after 2020). For the main Arlo.py script, this includes only that the Queue has been renamed to queue.

Example script: Writing the byte stream is different in Python 3 (no more implicit conversions between byte arrays and strings). I also changed the file name to be human-readable and to include the unique ID to prevent file name clashes for multiple cameras. Plus, the print statement now needs to have the string argument surrounded by ().

Also added the example download script in the readme as directly executable script file to the repository for easier testing.

More background info about the changes: https://www.andreasjakl.com/using-netgear-arlo-security-cameras-for-periodic-recording/

2017-07-18 21:46 UTC, jeffreydwalter requested changes
Other than my two comments (which are about the same thing), everything looks good. Thanks for contributing!

2017-07-18 21:46 UTC, jeffreydwalter commented on README.md
> +		#	 with open(videofilename+'.mp4', 'w') as f:
Minor tweak, but maybe we should append .mp4 to videofilename on line 51 where you assign videofilename so we don't have to keep appending it.

2017-07-18 21:46 UTC, jeffreydwalter commented on arlo-download.py
> +		videofilename = datetime.datetime.fromtimestamp(int(recording['name'])//1000).strftime('%Y-%m-%d %H-%M-%S') + ' ' + recording['uniqueId']
Same as in the README. Let's append the .mp4 to videofilename, so we can stop appending it all over the place below.

2017-07-18 21:47 UTC, jeffreydwalter requested changes

2017-07-18 21:47 UTC, jeffreydwalter commented on arlo-download.py
> +from datetime import timedelta, date
Might be good to move this script to an examples folder.

2017-07-18 21:50 UTC, jeffreydwalter commented
Are these changes breaking change for Python 2? If so, perhaps we should include an Arlo.py for both versions of Python?

2017-07-19 07:17 UTC, andijakl commented
Thanks for your comments! I've addressed these and made another commit.

I now kept the origional Python 2 file as "Arlo-Python2.py". Not sure if it'd be possible to have a version that works on both, as the "queue" package was renamed and the division import from future is no longer needed. So out of the box, the new Python 3 version wouldn't run in 2. But I feel it's better to have the Python 3 version as default by now.

For the download example, I'm assuming that the udpated version should also work fine with Python 2. The now mandatory paranthesis around the text of the print statement have been allowed in Python 2 as well. The additional buffer statement for writing the byte array to the file has been available in Python 2 already, so I think the code example should work fine also with the old Python version!

2017-07-20 18:57 UTC, jeffreydwalter commented
Instead of having two versions would it be possible to do something like this:
```
if sys.version[0] == '2':
    import Queue as queue
else:
    import queue as queue
```
?

2017-07-24 06:05 UTC, andijakl commented
Good idea - changed that in the Arlo.py script - still works fine (with Python 3). Removed the other extra copy of the script for Python 2.

2017-07-25 19:07 UTC, jeffreydwalter approved these changes
Looks great! Thanks for contributing!

2017-07-25 19:07 UTC, merged